name: Build Wasmer for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: Build Wasmer for Android
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-linux-android

    - name: Install Android NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk

    - name: Build Wasmer for Android
      run: |
        cargo install cargo-ndk
        cargo ndk -t arm64-v8a -o ./jniLibs build --release
        
    - name: Upload Artifact-1
      uses: actions/upload-artifact@v3
      with:
        name: wasmer-android
        path: ./jniLib
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: wasmer-android
        path: target/aarch64-linux-android/release/
